name: Docker Image CI
 
on:
  push:
    branches: [ development ]
  

jobs:

  build:

    runs-on: dotnet

    steps:
      - uses: actions/checkout@v2
      -
         name: Login to registry
         uses: docker/login-action@v1
         with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}
    
      - name: Build the Docker image    
        env:
          API_URL: ${{ secrets.API_URL }}
          
        run: |  
               docker build . --tag ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sme-prova-serap-front
               docker push ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sme-prova-serap-front
        
  deploy:
    runs-on: dotnet        
    needs: [ build ]
    environment:
      name: development
    steps:
      - name: Run an adjust of kubernetes dev
        env: # Ou como uma variável de ambiente
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
        run: |
          sed -e "s/\${RANCHER_URL}/$RANCHER_URL/" -e "s/\${RANCHER_TOKEN}/$RANCHER_TOKEN/" /runner/config_template > /runner/.kube/config                
      - 
       name: Change Images
       run: |
         kubectl rollout restart deployment/sme-prova-serap-front -n sme-serap-estudante           
         rm -f /runner/.kube/config      
